config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  get '/contact', to: 'static_pages#contact', as: 'contact'

  resources :actors

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :experiences
  validates_presence_of :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :actor
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
    render :index
  end

  def show
    @actor = Actor.find(params[:id])
  end

  def new
    @actor = Actor.new
  end

  def create
    @actor = Actor.new(actor_params)
    if @actor.save
      redirect_to actor_path(@actor)
    else
      render :new
    end
  end

  def edit
    @actor = Actor.find(params[:id])
  end

  def update
    @actor = Actor.find(params[:id])
    if @actor.update(actor_params)
      redirect_to actor_path(@actor)
    else
      render :edit
    end
  end

  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy
    redirect_to actors_path
  end

  private

  def actor_params
    #binding.pry
    params.require(:actor).permit(:name, :age, :gender, :day_rate, :agent)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/actors/_form.html.erb
<% if @actor.errors.any? %>
  <ul>
    <% @actor.errors.full_messages.each do |error| %>
    <li> <%= error %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @actor do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <br>
  <br>
  <%= f.label :age %>
  <%= f.number_field :age %>

  <br>
  <br>
  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <br>
  <br>
  <%= f.label :day_rate %>
  <%= f.number_field :day_rate %>

  <br>
  <br>
  <%= f.label :agent %>
  <%= f.check_box :agent %>

  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/actors/edit.html.erb
<h1> Editing <%= @actor.name %>'s Profile </h1>

<%= render(partial: 'form') %>

app/views/actors/index.html.erb
<h1>List of Actor Profiles</h1>
<h2>Click on name to view Profile</h2>

<% if @actors.any? %>
  <ul>
  <% @actors.each do |actor| %>
  <li>
    <%= link_to actor.name, actor_path(actor) %>
  </li>
  <% end %>
  </ul>
<% else %>
  <!-- empty array, no people in the database -->

<% end %>

<h2><%= link_to 'Create Actor Profile', new_actor_path %></h2>

app/views/actors/new.html.erb
<h1>Create New Actor Profile</h1>

<%= render(partial: 'form') %>

app/views/actors/show.html.erb
<h1><%= @actor.name %>'s Profile </h1>

<table>
  <thead>
    <tr>
      <th>Age</th>
      <th>Gender</th>
      <th>Day Rate</th>
      <th>Agent</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> <%= @actor.age %> </td>
      <td> <%= @actor.gender %> </td>
      <td> <%= @actor.day_rate %> </td>
      <td> <%= @actor.agent %> </td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit Profile', edit_actor_path(@actor) %> |
<%= link_to 'Delete Profile', actor_path(@actor), method: :delete %>
<br />
<%= link_to 'All Actors', actors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Audition App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to 'Home', root_path %> |
      <%= link_to 'Profiles', actors_path %> |
      <%= link_to 'Contact Us', contact_path %> |
      <a href="http://www.google.com" target="_blank">Google!</a>
    </header>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Need to contact us?</h1>
<img src="http://p.fod4.com/p/media/877ebc4f55/NnM2HPr5RJOgIeIIR7n1_Bus%20Middle%20Finger.gif" alt="flip off" />

app/views/static_pages/home.html.erb
<h1>Welcome to Actor Hub!</h1>
<h2>Where D-level actors come to get C-level gigs!</h2>
<div>
  <img src="https://gubulldogblog.files.wordpress.com/2015/10/lets_do_this_creed.gif" alt="lets do this" />
</div>
<div class='button'> <%= link_to 'Enter', actors_path %> </div>